/** Generated from the Microsoft FORTRAN F6.3 reader used by COFECHA 6.06. */
const F63_NEGATIVE_ULP_BASE64 = "ACAABAAgEAgAAAAEAAFAAACAAAAAABAAAAADAIAwAAAAAABAAAAAAAAAAgAAAQAAAAAAAAUAgAICQAAFIIAKAAAAAAAgAAAQAAAIAAAAAAAAAAAABAAAAgAAAQAAAAAAAAAAgAAAiAARIAAAIkIEAASAiBAAABEgAgQAQEQAAAgAAAAAAAIAAAAEAAAAAAABAAAAAEAAAACAAAAAAAAgAAAAAAAIAAAAEAAAAAAABAAAAAAAAQAAAAIAAAAAgAAAAAAAIAAAAEAgICCAwEAAAIEBAAQCAgIIBAQEEBgIACAwAIBAQEAAgYCAAAIDAQAEBgAQCAgIIBAQECAAAABAAAAAgAAAAAAAAAAEAAAACAAAABAAAAAAAACAAAAAAAEAAAACAAAAAAAAEAAAACAAAABAAAAAAAAAAAIAAAAEAAAACAAAAAAAAEAAAACAAAAAAAEAAAAAAAAIAAAAEAAAACAAAAAAAAAAAQAAAAIAAAAEAAAAAAAAIAAAAEAAAACAAAAAAAAAAAQAAAAIAAAAEAgECgQABIBAIFAgECAAAAKBQIEAgAAQCAQKBAIEAEAgECgQABAAAoFAgUCAAAAIBAIFAgACQCAQKBAIEAAAgUCgQABAAAgEAgUCAQIAIBAIFAgACACBQKBAIEAAAAQCgQIBAAEABAIAAAAAAAAQAAAAAAAAgEAAAAAAAAAAAgAAAAAAABAIAAAAAAAAQAAAAAAAAAACAQAAAAAAAAgAAAAAAABAIAAAAAAAAAABAAAAAAAACAQAAAAAAAAgAAAAAAAAAIEAAAAAAAAABAAAAAAAACAQAAAAAAAAgAAAAAAAAAAEAgAAAAAAABAAAAAAAACAQAAAAAAAAAACAAAAAAAAEAgAAAAAAABAAAAAAAAAAAIBAAAAAAAACAAAAAAAAEAgAAAAAAAAAAEAAAAAAAAIBAAAAAAAACAAAAAAAAAAgQAAAAAAAAAEAAAAAAAAIBAAAAAAAACAAAAAAAAAAAQCAAAAAAAAEAAAAAAAAIBAAAAAAAAAAAIAAAAAAAAQCAAAAAAAAEAAAAAAAAAAAgFAIBCIRCAQCAAgEAAAQCAQCAQCkQgEAgEABAIAAAgEAoFAIBKBQCAAgEAAAACBQCAQCEQiEAgEABAIAAAgEAgEAoFIBAKBAAACAQAABAKBQCAQiUAgEABAIAAAgEAgEAgEIhEIBAIACAQAABAIBAKBQCQCgUAAAIEAAAACgUAgEIhEIBAIACAQAABAIBAIBAKRCAQCAQAEAgAACAQCgUAgEoFAIACAQAAAAIFAIBAIRCIQCAQAEAgAACAQCAQCgUgEAoEAAAIBAAAAEAgEAAAAAAAAAAAAAAAAAAKBAAAAAAAAAAAAAAAAAEAgEAAAAAAAAAAAAAAAAAAIBAIAAAAAAAAAAAAAAAAAgUAAAAAAAAAAAAAAAAAAIBAIAAAAAAAAAAAAAAAAAAQCAQAAAAAAAAAAAAAAAIBAIAAAAAAAAAAAAAAAAAAQCAQAAAAAAAAAAAAAAAAAAoEAAAAAAAAAAAAAAAAAQCAQAAAAAAAAAAAAAAAAAAgEAgAAAAAAAAAAAAAAAACBQAAAAAAAAAAAAAAAAAAgEAgAAAAAAAAAAAAAAAAABAIBAAAAAAAAAAAAAAAAgEAgAAAAAAAAAAAAAAA=";
const F63_POSITIVE_ULP_BASE64 = "IIYUwBKBglAEA4FIBGiAExACh4ABYsAQOADgHgLAjwkAKwQAlUIASiEArBQCUAoBYIWqoAJcVAEsqoBSVUBhggggRQSQIoIIMUEEmCACTBABpIgAUkQQISaIABNEgAkigBQRQEZEIsyMiFCRGDEjIlAmRsSISISZEREqEiMUBkJIKAiEkRAQCgJhJASEwkAICQWBMBICQkEgjISAUBgIIaEgEEZCQCgIhJEQEAoDISQUBMJICAgFgTASAkJhIISEgkAYCQGhIBAWGhg4LCRwcFDI4GCgkYHBQgMDh4UEDg4KGRwMNDIwWGhg4LCQwMFBIYODgUYGBgsNDBIJFAgkEmAQSKTAIJBAgUEigQKBRAIMAokUGAQSKDBIJFAgkEiAQSCRAoNAAgUGiQQKBBIJMAgkUmAQSKDAIJFAgUAiAQaBRAoMAgkUGCQSKBBIJMAgkEiBQSCBAoNEAgUCiQQYBBIpMAgkUGCQSKBAIJEAg0AiBQaBBAoMEgkUCCQSYBBIpMAgkECBQSKBAoFEAgwCiRSJRINCoUKlUCQaDAoVCpUikWhQKFSoFIpEg0GhQqFSJBINCoUKlUKRaDAoVChUikSiQaFQoVIoEg0GhQqFSpFINCgUKlQKRaLBoFChUCkSiQaFQoVKoUg0GBQqFCpFItGgUKgEg8EgEoFCIBAMBoEIFAqBYDAYRCJQCASCwSAQgUIhEAwGg0gECoFAMBgEIlAoBILBYBCJQCEQCAaDQAQKhUAwGAwiESgEAsFgEIhAoRAIBoNBJAKFQCAYDAIRKBQCwWAwiESgEAgEg0EgAoVCIBgMBpEIFAKBYDAIRKBQCASDwSASgUIgEAwGgQgUCoFgMBhEIlAIBILBIBCBQiEQDAaDSAQKgUAwGAQiUCgEgsFgEIlAIRAIBoNABAqFQDAYDCIRKAQCwWAQiEChEAgGg0EkAoVAIBgMAhEoFALBYDCIRKAQCASDQSAChUIgGAwGkQgUAoFgMAhEoFAIBIPBIBKBQiAQDAaBCBQKgWAwGEQiUAgEgsEgEIFCIRAMBoNIBAqBQDAYBCJQKASCwWASicFgMBqFQiQSiUwkEplMIjEYDEajUIhEIpGJRCKTSSQGg8FoFAqRSCQykUhkMonEYDAYjUIhEolEJhKJTCaRGAwGo1EoRCKRyEQikckkEoPBYDQKhUgkEplIJDKZRGIwGIxGoRCJRCITiUQmk0gMBoPRKBQikUhkIpHIZBKJwWAwGoVCJBKJTCQSmUwiMRgMRqNQiEQikYlEIpNJJAaDwWgUCpFIJDKRSGQyicRgMBiNQiESiUQmEolMJpEYDAajUShEIpHIRBAIhUKhUAgEBgOBSCQSCAQCoVAoFAqBwGAgEIlEAoFAIBQKhUIhEBgMBCKRSCAQCIRCoVAoBAKDgUAkEgkEAoFQKBQKhUBgMBCIRCKBQCAQCoVCoRAIDAYCkUgkEAgEQqFQKBQCgcFAIBKJBAKBQCgUCoVCIDAYCEQikUAgEAiFQqFQCAQGA4FIJBIIBAKhUCgUCoHAYCAQiUQCgUAgFAqFQiEQGAwEIpFIIBAIhEKhUCgEAoOBQCQSCQQCgVAoFAqFQGAwEIhEIoFAIBAKhUKhEAgMBgKRSCQQCARCoVAoFAKBwUAgEokEAoFAKBQKhUIgMBgIRCKRQCA=";
const F62_NEGATIVE_ULP_BASE64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
const F62_POSITIVE_ULP_BASE64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

const decodeBits = (encoded: string): Uint8Array => Uint8Array.from(
    atob(encoded),
    (character) => character.charCodeAt(0),
);
const f63NegativeUlp = decodeBits(F63_NEGATIVE_ULP_BASE64);
const f63PositiveUlp = decodeBits(F63_POSITIVE_ULP_BASE64);
const f62NegativeUlp = decodeBits(F62_NEGATIVE_ULP_BASE64);
const f62PositiveUlp = decodeBits(F62_POSITIVE_ULP_BASE64);
const floatBuffer = new ArrayBuffer(4);
const floatView = new Float32Array(floatBuffer);
const bitsView = new Uint32Array(floatBuffer);

const contains = (bits: Uint8Array, value: number): boolean => (
    (bits[value >> 3] & (1 << (value & 7))) !== 0
);

export const parseCofecha606TucsonWidth = (
    width: number,
    stopMarkerValue: number,
): number => {
    if (width < 0 && width !== stopMarkerValue) {
        return -parseCofecha606TucsonWidth(-width, stopMarkerValue);
    }
    if (stopMarkerValue === -9999
        && Number.isInteger(width)
        && width >= 0
        && width <= 9998
        && width !== 999) {
        floatView[0] = Math.fround(width / 1000);
        if (contains(f63NegativeUlp, width)) bitsView[0] -= 1;
        else if (contains(f63PositiveUlp, width)) bitsView[0] += 1;
        return floatView[0];
    }
    if (stopMarkerValue === 999
        && Number.isInteger(width)
        && width >= 0
        && width <= 998) {
        floatView[0] = Math.fround(width / 100);
        if (contains(f62NegativeUlp, width)) bitsView[0] -= 1;
        else if (contains(f62PositiveUlp, width)) bitsView[0] += 1;
        return floatView[0];
    }
    const scale = Math.fround(stopMarkerValue === 999 ? 0.01 : 0.001);
    return Math.fround(width * scale);
};
